language: python
# sudo false implies containerized builds
#sudo: false
python:
 - "3.5"
 - "3.6"
install:
    - pip install -r requirements_test.txt
# command to run tests
script:
    - py.test --cov=hue
