homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  customize: !include customize.yaml

frontend:
config:
http:
updater:
conversation:
history:
logbook:
sun:


sensor: !include sensor.yaml
group: !include groups.yaml
